version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-local
    ports:
      - "7000:7000"
    volumes:
      - ./static_public:/usr/share/nginx/static_public:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - gateway-local

networks:
  gateway-local:
    driver: bridge

